el archivo seguimientomanos funciona

el error
*File "c:\Users\usuario\Desktop\proyecto-3ro\Traductor-de-senas\Data.py", line 35, in <module>
    cv2.imshow("LENGUAJES VOCALES", frame)
cv2.error: OpenCV(4.11.0) D:\a\opencv-python\opencv-python\opencv\modules\highgui\src\window.cpp:973: error: (-215:Assertion failed) size.width>0 && size.height>0 in function 'cv::imshow'*
ha sido solucionado

me quede en el min 27:00, donde se nombran las imagenes a guardar
